package com.google.samples.app.iosched.tv

import com.google.samples.app.iosched.tv.di.DaggerTVAppComponent
import com.jakewharton.threetenabp.AndroidThreeTen
import dagger.android.AndroidInjector
import dagger.android.DaggerApplication
import timber.log.Timber

/**
 * Initialization of libraries
 */
class TVApplication : DaggerApplication() {

    override fun onCreate() {
        super.onCreate()

        // Timber, for loging
        if (BuildConfig.DEBUG) {
            Timber.plant(Timber.DebugTree())
        }

        // ThreeTenBP for times and dates
        AndroidThreeTen.init(this)
    }

    /**
     * Tell Dagger which [AndroidInjector] to use - in our case [TVComponent]. DaggerAppComponent
     * is a class generated by Dagger based on the [TVComponent] class.
     */
    override fun applicationInjector(): AndroidInjector<out DaggerApplication> {
        return DaggerTVAppComponent.builder().create(this)
    }
}